### ISSUE TITLE
DBC files for WoW 7.2.5 24742 frFR

### ISSUE THREAD

**Issue by Kelzano** [Marlamin/BuildBackup#2]
Hello Marlam !
I'm seeking your help once more as I would like to download the whole DBFilesClient folder from CASC in frFR locale for WoW 7.2.5 24742 and unfortunately, my CASCExplorer doesn't let me do that.
How would I be able to do that ?
Thanks in advance,
Kelzano.

**Comment by Marlamin** [comment]
I don't really support different locales either, sorry!
