### ISSUE TITLE
Can you upload a builded version

### ISSUE THREAD

**Issue by procrash** [Marlamin/BuildBackup#7]
Hi,

I tried to build your product to download some starcraft files. However the project structure is a little bit difficult for me to setup. I use VS2019 and NuGet is not even capable in fetching all the packages for version dot net 5.0 nor previous versions. Can you do me a favor and upload an executable with its dependencies for simplicity.

Regards,

Wolfgang

**Comment by Marlamin** [comment]
I'm afraid the current version is running on a pretty old .NET version so isn't really supported anymore. I'm working on a rework but it's not done yet. You can give the below ZIP a whirl, but I really can't support it if there's any issues. StarCraft likely isn't a supported application either so you'll definitely have to figure out how to compile things yourself.

[netcoreapp2.2.zip](https://github.com/Marlamin/BuildBackup/files/6126801/netcoreapp2.2.zip)

**Comment by procrash** [comment]
Thanks I'll give it a try...

**Comment by procrash** [comment]
Mimekit is missing now.
What needs to be changed that SC2 is working? I basically just want to grab some cache file data to get a specific linux version up and running? Do you know some other projects that I might be able to use to download the necessary files?

**Comment by Marlamin** [comment]
It will need the addition of the SC2 product as well as writing some code to support its filesystem structures (e.g. its install manifest, etc). I'd suggest CASCExplorer or CascView as an alternative, those might have support for it.

**Comment by procrash** [comment]
Ok thanks
